Add test of prometheus URL

diff --git a/.github/workflows/test-app-deployment.yml b/.github/workflows/test-app-deployment.yml
--- a/.github/workflows/test-app-deployment.yml
+++ b/.github/workflows/test-app-deployment.yml
@@ -70,3 +70,21 @@ jobs:
             exit 1
           fi
           echo "Backend health check passed."
+
+      - name: Set Prometheus URL
+        run: |
+          echo "PROMETHEUS_URL=$(az containerapp show \
+            --name orders-prometheus-dev-01 \
+            --resource-group orders-rg-app-dev-eus-01 \
+            --query properties.configuration.ingress.fqdn -o tsv)" >> $GITHUB_ENV          
+
+      - name: Test Prometheus HTTP response
+        run: |
+          echo "Testing Prometheus at $PROMETHEUS_URL ..."
+          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://$PROMETHEUS_URL:9090)
+          echo "Prometheus HTTP status: $STATUS_CODE"
+          if [ "$STATUS_CODE" -ne 200 ]; then
+            echo "Prometheus health check failed!"
+            exit 1
+          fi
+          echo "Prometheus health check passed."            
